# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# Platform.
platform: x64

clone_folder: c:\gopath\src\github.com\harshavardhana\os

# Environment variables
environment:
  GOROOT: c:\go17
  GOPATH: c:\gopath

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go17\bin;%PATH%
  - go version
  - go env
  - python --version

# To run your custom scripts instead of automatic MSBuild
build_script:
  # Compile
  - appveyor AddCompilationMessage "Starting Compile"
  - appveyor AddCompilationMessage "Compile Success"

# To run your custom scripts instead of automatic tests
test_script:
  # Unit tests
  - ps: Add-AppveyorTest "Unit Tests" -Outcome Running
  - go test -v -race github.com/harshavardhana/os/...
  - ps: Update-AppveyorTest "Unit Tests" -Outcome Passed

# to disable deployment
deploy: off
